spring:
  profiles:
    active: dev
  application:
    name: tiny-url
  datasource:
    url: jdbc:mysql://192.168.2.209:3306/vip?useUnicode=true&characterEncoding=utf8
    username: opsa
    password: pass123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: true
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      minimum-idle: 100
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapperLocations: classpath*:sqlmap/*.xml
  type-aliases-package: com.wujunshen.tinyurl.entity

server:
  port: 8012
tu:
  domain: http://localhost:8012
  tinyUrlDomain: http://localhost:8012/t/
#swagger config
swagger:
  enable: true
  contextPath: /
  #输入目前已知所有版本号集合,即使重复了也可以,有去重功能
  versions: v1.0,v1.1,v1.2,v1.0
  #缺省配置内容为:frank_wjs@hotmail.com
  contact-email: frank_wjs@hotmail.com
  #缺省配置内容为:黑暗浪子
  contact-name: 如有任何疑问，请联系我
  #缺省配置内容为:https://www.iteye.com/blog/user/darkranger
  contact-url: http://www.google.com
  #缺省配置内容为:文档内容仅供参考
  description: 接口文档说明
  #缺省配置内容为:Apache License Version 2.0
  license: license
  #缺省配置内容为:http://www.apache.org/licenses/LICENSE-2.0.html
  license-url: http://www.license.com
  #缺省配置内容为:API文档
  title: 自定义标题名
  #redis settings
redis:
  host: 192.168.3.206
  port: 6300
  password:
#snowflake settings
generate:
  worker: 100